jobs:
  diff:
    outputs:
      hash-main: ${{ steps.hash-main.outputs.hash-main }}
      hash-master: ${{ steps.hash-master.outputs.hash-master }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      id: hash-master
      name: Hash the master branch
      run: 'hash_master=$( git rev-parse origin/master )

        echo "$hash_master"

        echo "hash-master=$hash_master" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      id: hash-main
      name: Hash the main branch
      run: 'hash_main=$( git rev-parse origin/main )

        echo "$hash_main"

        echo "hash-main=$hash_main" >> $GITHUB_OUTPUT

        '
  sync:
    if: needs.diff.outputs.hash-master != needs.diff.outputs.hash-main
    needs: diff
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Checkout master
      run: git checkout master
    - continue-on-error: true
      name: Sync master to main
      run: git push origin master:main
name: Sync master to main
on:
  repository_dispatch:
    types: trigger-ga___main.yml
